name: Update Notebooks
on:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  update-notebooks:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    steps:

    - name: See event name
      run: |
        echo "title ${title}"
        echo "actor ${actor}"
        echo "event_name ${event_name}"
      env:
        title: ${{ github.event.issue.title }}
        actor: ${{ github.actor }}
        event_name: ${{ github.event_name }}

    - name: Copy Repository Contents
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6

    - name: install dependencies
      run: |
        sudo apt-get update -y
        pip3 install pandas numpy ipykernel jupyter altair altair_saver
        python3 -m ipykernel install --user --name python3
        sudo chmod -R 777 .

    - name: update notebooks
      id: update_nb
      run: |
        npm run all

    - name: save notebooks & images
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add data/chart_*.json
        git add data/corin_data.csv
        git commit -m "[bot] refresh notebooks" || echo "No changes to commit"
        git push -f || echo "No changes to push"
